export const products = [
    { id: 1, name: "Багет классический", category: "bread", price: 45, weight: 250, allergens: ["gluten"], vegan: false, image: "assets/images/baguette.svg", popular: true, new: false, description: "Традиционный французский багет с хрустящей корочкой" },
    { id: 2, name: "Хлеб ржаной", category: "bread", price: 65, weight: 500, allergens: ["gluten"], vegan: true, image: "assets/images/rye-bread.svg", popular: true, new: false, description: "Настоящий ржаной хлеб на натуральной закваске" },
    { id: 3, name: "Круассан масло", category: "pastry", price: 120, weight: 80, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/croissant.svg", popular: true, new: false, description: "Слоёное тесто с маслом 82% жирности" },
    { id: 4, name: "Веганский круассан", category: "pastry", price: 110, weight: 75, allergens: ["gluten"], vegan: true, image: "assets/images/vegan-croissant.svg", popular: false, new: true, description: "Круассан без животных продуктов" },
    { id: 5, name: "Торт Наполеон", category: "cake", price: 850, weight: 1000, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/napoleon-cake.svg", popular: true, new: false, description: "Многослойный торт с нежным заварным кремом" },
    { id: 6, name: "Безглютеновый торт", category: "cake", price: 950, weight: 800, allergens: [], vegan: true, image: "assets/images/gluten-free-cake.svg", popular: false, new: true, description: "Торт на основе миндальной муки с ягодами" },
    { id: 7, name: "Эспрессо", category: "drink", price: 150, weight: 50, allergens: [], vegan: true, image: "assets/images/espresso.svg", popular: true, new: false, description: "Крепкий итальянский кофе арабика" },
    { id: 8, name: "Матча латте", category: "drink", price: 200, weight: 200, allergens: ["lactose"], vegan: false, image: "assets/images/matcha-latte.svg", popular: false, new: true, description: "Японский зелёный чай с молоком и мятой" },
    { id: 9, name: "Киш с лососем", category: "pastry", price: 180, weight: 150, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/salmon-quiche.svg", popular: true, new: false, description: "Открытый пирог с лососем и шпинатом" },
    { id: 10, name: "Фокачча", category: "bread", price: 90, weight: 300, allergens: ["gluten"], vegan: true, image: "assets/images/focaccia.svg", popular: false, new: false, description: "Итальянский хлеб с розмарином и оливками" },
    { id: 11, name: "Чизкейк", category: "cake", price: 320, weight: 150, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/cheesecake.svg", popular: true, new: false, description: "Классический нью-йоркский чизкейк" },
    { id: 12, name: "Безлактозный капучино", category: "drink", price: 180, weight: 200, allergens: [], vegan: false, image: "assets/images/lactose-free-cappuccino.svg", popular: false, new: true, description: "На основе миндального молока с корицей" },
    { id: 13, name: "Чиабатта", category: "bread", price: 55, weight: 280, allergens: ["gluten"], vegan: true, image: "assets/images/ciabatta.svg", popular: false, new: false, description: "Итальянский хлеб с крупными порами и хрустящей корочкой" },
    { id: 14, name: "Зерновой хлеб", category: "bread", price: 75, weight: 550, allergens: ["gluten"], vegan: true, image: "assets/images/seeded-bread.svg", popular: false, new: false, description: "Пять видов зёрен и семечек в мягком тесте" },
    { id: 15, name: "Даниш с вишней", category: "pastry", price: 140, weight: 90, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/cherry-danish.svg", popular: true, new: false, description: "Слоёное тесто с вишнёвой начинкой и глазурью" },
    { id: 16, name: "Эклер", category: "pastry", price: 130, weight: 70, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/eclair.svg", popular: false, new: true, description: "Заварное тесто с ванильным кремом и шоколадом" },
    { id: 17, name: "Синнабон", category: "pastry", price: 160, weight: 120, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/cinnamon-roll.svg", popular: true, new: false, description: "Булочка с корицей и сливочным крем-чизом" },
    { id: 18, name: "Профитроли", category: "pastry", price: 200, weight: 100, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/profiteroles.svg", popular: false, new: false, description: "Набор из трёх эклеров с разными начинками" },
    { id: 19, name: "Тирамису", category: "cake", price: 380, weight: 180, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/tiramisu.svg", popular: true, new: false, description: "Слоёный десерт с маскарпоне и кофе" },
    { id: 20, name: "Макарон (набор)", category: "cake", price: 450, weight: 120, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/macarons.svg", popular: false, new: true, description: "Набор из 6 французских миндальных пирожных" },
    { id: 21, name: "Павлова", category: "cake", price: 420, weight: 160, allergens: [], vegan: true, image: "assets/images/pavlova.svg", popular: false, new: false, description: "Безе со взбитыми сливками и свежими ягодами" },
    { id: 22, name: "Медовик", category: "cake", price: 350, weight: 200, allergens: ["gluten", "lactose"], vegan: false, image: "assets/images/honey-cake.svg", popular: true, new: false, description: "Классический многослойный мёдный торт" },
    { id: 23, name: "Горячий шоколад", category: "drink", price: 220, weight: 250, allergens: ["lactose"], vegan: false, image: "assets/images/hot-chocolate.svg", popular: true, new: false, description: "Бельгийский шоколад с молоком и маршмеллоу" },
    { id: 24, name: "Лимонад домашний", category: "drink", price: 170, weight: 300, allergens: [], vegan: true, image: "assets/images/lemonade.svg", popular: false, new: true, description: "Лимон, мята и имбирь на игристой воде" }
];

export const allProducts = [...products];
